<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_packages = $this->getPackages(); ?>
<div class="page-title">
    <h1><?php echo $this->__('Composer Packages') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_packages->getSize()): ?>
    <table class="data-table" id="my-packages-table">
        <col width="1" />
        <col />
        <col width="1" />
        <thead>
        <tr>
            <th><span class="nobr"><?php echo $this->__('Order ID') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Description') ?></span></th>
            <th><?php echo $this->__('Package Name') ?></th>
            <th><?php echo $this->__('Last Available version') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_packages as $_package): ?>
            <tr>
                <td><?php echo $_package->getIncrementId() ?></td>
                <td><?php echo $_package->getDescription() ?> (<?php echo $_package->getVersion() ?> )</td>
                <td><?php echo $_package->getName() ?></td>
                <td><?php echo $_package->getLastAllowedVersion() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-packages-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('There are no packages available'); ?></p>
<?php endif ?>
