<?php
$packages  = $this->getPackages();
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
    <tr>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Magento Extension') ?></th>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Package Name') ?></th>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Version') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($packages as $package):?>
        <tr>
            <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $package->getDescription();?></td>
            <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $package->getName();?></td>
            <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $package->getVersion();?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

